version: '3.9'

services:
  postgres-sql:
    restart: always
    image: postgres:16.2
    environment:
      POSTGRES_DB: dbSql
      POSTGRES_USER: dbUser
      POSTGRES_PASSWORD: dbPassword
    ports:
      - "5435:5432"
